# Project: First_Graphics
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Question_2_Draw_Flowers.o ../Gen/Bloodshedv5/include/graphics/ccc_msw.o ../Gen/Bloodshedv5/include/graphics/ccc_shap.o
LINKOBJ  = Question_2_Draw_Flowers.o ../Gen/Bloodshedv5/include/graphics/ccc_msw.o ../Gen/Bloodshedv5/include/graphics/ccc_shap.o
LIBS     = -L"C:/Users/johns/Desktop/GENE_121/Dev-Cpp/MinGW64/lib32" -L"C:/Users/johns/Desktop/GENE_121/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -mwindows -m32
INCS     = -I"C:/Users/johns/Desktop/GENE_121/Dev-Cpp/MinGW64/include" -I"C:/Users/johns/Desktop/GENE_121/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/johns/Desktop/GENE_121/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/johns/Desktop/GENE_121/Gen/Bloodshedv5/include"
CXXINCS  = -I"C:/Users/johns/Desktop/GENE_121/Dev-Cpp/MinGW64/include" -I"C:/Users/johns/Desktop/GENE_121/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/johns/Desktop/GENE_121/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/johns/Desktop/GENE_121/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"C:/Users/johns/Desktop/GENE_121/Gen/Bloodshedv5/include"
BIN      = First_Graphics.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Question_2_Draw_Flowers.o: Question_2_Draw_Flowers.cpp
	$(CPP) -c Question_2_Draw_Flowers.cpp -o Question_2_Draw_Flowers.o $(CXXFLAGS)

../Gen/Bloodshedv5/include/graphics/ccc_msw.o: ../Gen/Bloodshedv5/include/graphics/ccc_msw.cpp
	$(CPP) -c ../Gen/Bloodshedv5/include/graphics/ccc_msw.cpp -o ../Gen/Bloodshedv5/include/graphics/ccc_msw.o $(CXXFLAGS)

../Gen/Bloodshedv5/include/graphics/ccc_shap.o: ../Gen/Bloodshedv5/include/graphics/ccc_shap.cpp
	$(CPP) -c ../Gen/Bloodshedv5/include/graphics/ccc_shap.cpp -o ../Gen/Bloodshedv5/include/graphics/ccc_shap.o $(CXXFLAGS)
